### ISSUE TITLE
Story names could use prefixes

### ISSUE THREAD

**Issue by Jarry1250** [yuvipanda/WPSignpost#18] opened 2012-08-15 14:21 UTC
To make it clearer which story comes from which regular report, it might be an idea to prefix the titles on the main page. Such prefixes might include Tech: , N&N: , Features:, ITN: , Discussions: or somesuch.

**Comment by yuvipanda** [comment] 2012-08-25 20:25
Duplicate of #35 (better desc there)

**Closed as completed by yuvipanda** 2012-08-25 20:25 UTC
