### ISSUE TITLE
headline links to Wikipedia are broken

### ISSUE THREAD

**Issue by ragesoss** [yuvipanda/WPSignpost#44] opened 2012-08-25 16:20 UTC
The link from an individual article in the app to that article on Wikipedia isn't formatted right. An example of the link my browser opens: http://en.wikipedia.org/en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2012-08-20/Op-ed

**Comment by yuvipanda** [comment] 2012-08-25 18:28
Duplicate of #26. Been fixed :)

**Closed as completed by yuvipanda** 2012-08-25 18:28 UTC
